Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false

# This is because mode describe blocks go over the limit
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'Guardfile'
    - 'Gemfile'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*.rb'
    - 'bin/*'

